version: "3.8"

x-hz-common-settings: &hz-common-settings
  image: hazelcast/hazelcast:latest
  networks:
    - hazelcast-network

x-common-env: &hz-common-env
  HZ_CLUSTERNAME: dev

x-consul-env: &consul-env
  CONSUL_HOST: "consul"
  CONSUL_PORT: 8500

services:
  hazel-node-1:
    <<: *hz-common-settings
    container_name: hazel-node-1
    environment:
      <<: *hz-common-env
      <<: *consul-env
      HZ_NETWORK_PUBLICADDRESS: "${HOST_IP}:5701"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:5701/hazelcast/health/node-state",
        ]
      interval: 5s
      timeout: 1s
      retries: 25
      start_period: 10s
    ports:
      - "5701:5701"

  hazel-node-2:
    <<: *hz-common-settings
    container_name: hazel-node-2
    environment:
      <<: *hz-common-env
      <<: *consul-env
      HZ_NETWORK_PUBLICADDRESS: "${HOST_IP}:5702"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:5702/hazelcast/health/node-state",
        ]
      interval: 5s
      timeout: 1s
      retries: 25
      start_period: 10s
    ports:
      - "5702:5701"

  hazel-node-3:
    <<: *hz-common-settings
    container_name: hazel-node-3
    environment:
      <<: *hz-common-env
      <<: *consul-env
      HZ_NETWORK_PUBLICADDRESS: "${HOST_IP}:5703"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:5703/hazelcast/health/node-state",
        ]
      interval: 5s
      timeout: 1s
      retries: 25
      start_period: 10s
    ports:
      - "5703:5701"

  hazel-node-mq:
    image: hazelcast/hazelcast:latest
    container_name: hazel-node-mq
    networks:
      - services-network
    environment:
      <<: *consul-env
      HZ_CLUSTERNAME: mq
      HZ_NETWORK_PUBLICADDRESS: "${HOST_IP}:5704"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:5704/hazelcast/health/node-state",
        ]
      interval: 5s
      timeout: 1s
      retries: 25
      start_period: 10s
    ports:
      - "5704:5701"

  management-center:
    image: hazelcast/management-center:latest
    container_name: hazel-management-center
    ports:
      - "8080:8080"
    networks:
      - hazelcast-network
      - services-network
    environment:
      <<: *consul-env
    depends_on:
      - hazel-node-1
      - hazel-node-mq

  logging-service-1:
    image: logging-service
    build:
      context: .
      dockerfile: services/logging_service/Dockerfile
    container_name: logging-service-1
    environment:
      HZ_NETWORK_PUBLICADDRESS: "${HOST_IP}:5701"
      PORT: 8980
      <<: *consul-env
    networks:
      - hazelcast-network
      - services-network
    volumes:
      - .:/code
    depends_on:
      hazel-node-1:
        condition: service_healthy
      consul:
        condition: service_started
    ports:
      - "8980:8980"

  logging-service-2:
    image: logging-service
    build:
      context: .
      dockerfile: services/logging_service/Dockerfile
    container_name: logging-service-2
    environment:
      HZ_NETWORK_PUBLICADDRESS: "${HOST_IP}:5702"
      PORT: 8981
      <<: *consul-env
    networks:
      - hazelcast-network
      - services-network
    volumes:
      - .:/code
    depends_on:
      hazel-node-2:
        condition: service_healthy
      consul:
        condition: service_started
    ports:
      - "8981:8981"

  logging-service-3:
    image: logging-service
    build:
      context: .
      dockerfile: services/logging_service/Dockerfile
    container_name: logging-service-3
    environment:
      HZ_NETWORK_PUBLICADDRESS: "${HOST_IP}:5703"
      PORT: 8982
      <<: *consul-env
    networks:
      - hazelcast-network
      - services-network
    volumes:
      - .:/code
    depends_on:
      hazel-node-3:
        condition: service_healthy
      consul:
        condition: service_started

    ports:
      - "8982:8982"

  messages-service-1:
    image: messages-service
    build:
      context: .
      dockerfile: services/message_service/Dockerfile
    container_name: messages-service-1
    environment:
      HZ_NETWORK_PUBLICADDRESS: "${HOST_IP}:5704"
      PORT: 8180
      <<: *consul-env
    networks:
      - services-network
    volumes:
      - .:/code
    depends_on:
      - consul
      - hazel-node-mq
    ports:
      - "8180:8180"

  messages-service-2:
    image: messages-service
    build:
      context: .
      dockerfile: services/message_service/Dockerfile
    container_name: messages-service-2
    environment:
      HZ_NETWORK_PUBLICADDRESS: "${HOST_IP}:5704"
      PORT: 8181
      <<: *consul-env
    networks:
      - services-network
    volumes:
      - .:/code
    depends_on:
      - consul
      - hazel-node-mq
    ports:
      - "8181:8181"

  facade-service:
    image: facade-service
    build:
      context: .
      dockerfile: services/facade_service/Dockerfile
    container_name: facade-service
    environment:
      HZ_NETWORK_PUBLICADDRESS: "${HOST_IP}:5704"
      PORT: 8000
      <<: *consul-env
    networks:
      - services-network
    volumes:
      - .:/code
    depends_on:
      - consul
      - logging-service-1
      - messages-service-1
      - hazel-node-mq
    ports:
      - "8000:8000"

  consul:
    image: hashicorp/consul:latest
    command: "/bin/sh -c 'sh /consul-population.sh'"
    container_name: consul-server
    volumes:
      - ./consul-population.sh:/consul-population.sh
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - hazelcast-network
      - services-network

networks:
  hazelcast-network:
    driver: bridge
    name: hazelcast-network

  services-network:
    driver: bridge
    name: services-network
