version: "3.8"

x-hz-common-settings: &hz-common-settings
  image: hazelcast/hazelcast:latest
  networks:
    - hazelcast-network

x-common-env: &hz-common-env
  HZ_CLUSTERNAME: ${HZ_LOGGING_CLUSTER_NAME}

x-consul-env: &consul-env
  CONSUL_HOST: "${CONSUL_HOST}"
  CONSUL_PORT: "${CONSUL_PORT}"

x-healthcheck: &healthcheck
  healthcheck:
    test:
      [
        "CMD",
        "curl",
        "-f",
        "http://localhost:${HZ_NODE}/hazelcast/health/node-state",
      ]
    interval: 3s
    timeout: 1s
    retries: 10
    start_period: 5s

services:
  hazel-node-1:
    <<: *hz-common-settings
    container_name: hazel-node-1
    environment:
      <<: *hz-common-env
      HZ_NETWORK_PUBLICADDRESS: "hazel-node-1:${HZ_NODE}"
    <<: *healthcheck

  hazel-node-2:
    <<: *hz-common-settings
    container_name: hazel-node-2
    environment:
      <<: *hz-common-env
      HZ_NETWORK_PUBLICADDRESS: "hazel-node-2:${HZ_NODE}"
    <<: *healthcheck

  hazel-node-3:
    <<: *hz-common-settings
    container_name: hazel-node-3
    environment:
      <<: *hz-common-env
      HZ_NETWORK_PUBLICADDRESS: "hazel-node-3:${HZ_NODE}"
    <<: *healthcheck

  hazel-node-mq:
    image: hazelcast/hazelcast:latest
    container_name: hazel-node-mq
    networks:
      - services-network
    environment:
      HZ_NETWORK_PUBLICADDRESS: "hazel-node-mq:${HZ_NODE}"
      HZ_CLUSTERNAME: "${HZ_MQ_CLUSTER_NAME}"
    <<: *healthcheck

  management-center:
    image: hazelcast/management-center:latest
    container_name: hazel-management-center
    ports:
      - "8080:8080"
    networks:
      - hazelcast-network
      - services-network
    depends_on:
      hazel-node-1:
        condition: service_started
      hazel-node-mq:
        condition: service_started

  logging-service-1:
    image: logging-service
    build:
      context: .
      dockerfile: services/logging_service/Dockerfile
    container_name: logging-service-1
    environment:
      HZ_NETWORK_PUBLICADDRESS: "hazel-node-1:${HZ_NODE}"
      PORT: 8980
      <<: *consul-env
    ports:
      - "8980:8980"
    networks:
      - hazelcast-network
      - services-network
    volumes:
      - .:/code
    depends_on:
      hazel-node-1:
        condition: service_healthy
      consul:
        condition: service_healthy

  logging-service-2:
    image: logging-service
    build:
      context: .
      dockerfile: services/logging_service/Dockerfile
    container_name: logging-service-2
    environment:
      HZ_NETWORK_PUBLICADDRESS: "hazel-node-2:${HZ_NODE}"
      PORT: 8981
      <<: *consul-env
    ports:
      - "8981:8981"
    networks:
      - hazelcast-network
      - services-network
    volumes:
      - .:/code
    depends_on:
      hazel-node-2:
        condition: service_healthy
      consul:
        condition: service_healthy

  logging-service-3:
    image: logging-service
    build:
      context: .
      dockerfile: services/logging_service/Dockerfile
    container_name: logging-service-3
    environment:
      HZ_NETWORK_PUBLICADDRESS: "hazel-node-3:${HZ_NODE}"
      PORT: 8982
      <<: *consul-env
    ports:
      - "8982:8982"
    networks:
      - hazelcast-network
      - services-network
    volumes:
      - .:/code
    depends_on:
      hazel-node-3:
        condition: service_healthy
      consul:
        condition: service_healthy

  messages-service-1:
    image: messages-service
    build:
      context: .
      dockerfile: services/message_service/Dockerfile
    container_name: messages-service-1
    environment:
      HZ_NETWORK_PUBLICADDRESS: "hazel-node-mq:${HZ_NODE}"
      PORT: 8180
      <<: *consul-env
    ports:
      - "8180:8180"
    networks:
      - services-network
    volumes:
      - .:/code
    depends_on:
      consul:
        condition: service_healthy
      hazel-node-mq:
        condition: service_healthy

  messages-service-2:
    image: messages-service
    build:
      context: .
      dockerfile: services/message_service/Dockerfile
    container_name: messages-service-2
    environment:
      HZ_NETWORK_PUBLICADDRESS: "hazel-node-mq:${HZ_NODE}"
      PORT: 8181
      <<: *consul-env
    ports:
      - "8181:8181"
    networks:
      - services-network
    volumes:
      - .:/code
    depends_on:
      consul:
        condition: service_healthy
      hazel-node-mq:
        condition: service_healthy

  facade-service:
    image: facade-service
    build:
      context: .
      dockerfile: services/facade_service/Dockerfile
    container_name: facade-service
    environment:
      HZ_NETWORK_PUBLICADDRESS: "hazel-node-mq:${HZ_NODE}"
      PORT: 8000
      <<: *consul-env
    ports:
      - "8000:8000"
    networks:
      - services-network
    volumes:
      - .:/code
    depends_on:
      consul:
        condition: service_healthy
      hazel-node-mq:
        condition: service_healthy

  consul:
    image: hashicorp/consul:latest
    command: "/bin/sh -c 'sh /consul-population.sh'"
    container_name: consul-server
    volumes:
      - ./consul-population.sh:/consul-population.sh
    ports:
      - "${CONSUL_PORT}:${CONSUL_PORT}"
      - "8600:8600/udp"
    networks:
      - hazelcast-network
      - services-network
    environment:
      HZ_LOGGING_CLUSTER_NAME: "${HZ_LOGGING_CLUSTER_NAME}"
      HZ_LOGGING_MAPPING_NAME: "${HZ_LOGGING_MAPPING_NAME}"

      HZ_MQ_CLUSTER_NAME: "${HZ_MQ_CLUSTER_NAME}"
      HZ_MQ_QUEUE_NAME: "${HZ_MQ_QUEUE_NAME}"

      CONSUL_ESSENTIAL_KEY: "${CONSUL_ESSENTIAL_KEY}"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://${CONSUL_HOST}:${CONSUL_PORT}/v1/kv/${CONSUL_ESSENTIAL_KEY}",
        ]
      interval: 5s
      timeout: 1s
      retries: 3

networks:
  hazelcast-network:
    driver: bridge
    name: hazelcast-network

  services-network:
    driver: bridge
    name: services-network
