version: "3.8"

x-hz-common-settings: &hz-common-settings
  image: hazelcast/hazelcast:latest
  networks:
    - hazelcast-network

x-common-env: &hz-common-env
  HZ_CLUSTERNAME: ${HZ_LOGGING_CLUSTER_NAME}

x-consul-env: &consul-env
  CONSUL_HOST: "${CONSUL_HOST}"
  CONSUL_PORT: "${CONSUL_PORT}"

x-healthcheck: &healthcheck
  healthcheck:
    test:
      [
        "CMD",
        "curl",
        "-f",
        "http://localhost:${HZ_NODE}/hazelcast/health/node-state",
      ]
    interval: 3s
    timeout: 1s
    retries: 10
    start_period: 5s

x-logging-common-settings: &logging-common-settings
  image: logging-service
  build:
    context: .
    dockerfile: services/logging_service/Dockerfile
  environment:
    HZ_NETWORK_PUBLICADDRESS: "hazel-node-log-1:${HZ_NODE}"
    PORT: ${LOGGING_PORT}
    <<: *consul-env
  networks:
    - hazelcast-network
    - services-network
  volumes:
    - .:/code
  depends_on:
    hazel-node-log-1:
      condition: service_healthy
    consul:
      condition: service_healthy

x-messaging-common-settings: &messaging-common-settings
  image: messages-service
  build:
    context: .
    dockerfile: services/message_service/Dockerfile
  environment:
    HZ_NETWORK_PUBLICADDRESS: "hazel-node-mq:${HZ_NODE}"
    PORT: "${MESSAGES_PORT}"
    <<: *consul-env
  networks:
    - services-network
  volumes:
    - .:/code
  depends_on:
    consul:
      condition: service_healthy
    hazel-node-mq:
      condition: service_healthy

x-facade-common-settings: &facade-common-settings
  image: facade-service
  build:
    context: .
    dockerfile: services/facade_service/Dockerfile
  environment:
    HZ_NETWORK_PUBLICADDRESS: "hazel-node-mq:${HZ_NODE}"
    PORT: ${FACADE_PORT}
    <<: *consul-env
  networks:
    - services-network
  volumes:
    - .:/code
  depends_on:
    consul:
      condition: service_healthy
    hazel-node-mq:
      condition: service_healthy

services:
  hazel-node-log-1:
    <<: *hz-common-settings
    container_name: hazel-node-log-1
    environment:
      <<: *hz-common-env
      HZ_NETWORK_PUBLICADDRESS: "hazel-node-log-1:${HZ_NODE}"
    <<: *healthcheck

  hazel-node-log-2:
    <<: *hz-common-settings
    container_name: hazel-node-log-2
    environment:
      <<: *hz-common-env
      HZ_NETWORK_PUBLICADDRESS: "hazel-node-log-2:${HZ_NODE}"
    <<: *healthcheck

  hazel-node-log-3:
    <<: *hz-common-settings
    container_name: hazel-node-log-3
    environment:
      <<: *hz-common-env
      HZ_NETWORK_PUBLICADDRESS: "hazel-node-log-3:${HZ_NODE}"
    <<: *healthcheck

  hazel-node-mq:
    image: hazelcast/hazelcast:latest
    container_name: hazel-node-mq
    networks:
      - services-network
    environment:
      HZ_NETWORK_PUBLICADDRESS: "hazel-node-mq:${HZ_NODE}"
      HZ_CLUSTERNAME: "${HZ_MQ_CLUSTER_NAME}"
    <<: *healthcheck

  management-center:
    image: hazelcast/management-center:latest
    container_name: hazel-management-center
    ports:
      - "8080:8080"
    networks:
      - hazelcast-network
      - services-network
    depends_on:
      hazel-node-log-1:
        condition: service_started
      hazel-node-mq:
        condition: service_started

  logging-service-1:
    <<: *logging-common-settings
    ports:
      - "8101:${LOGGING_PORT}"
  logging-service-2:
    <<: *logging-common-settings
    ports:
      - "8102:${LOGGING_PORT}"
  logging-service-3:
    <<: *logging-common-settings
    ports:
      - "8103:${LOGGING_PORT}"

  messages-service-1:
    <<: *messaging-common-settings
    ports:
      - "8181:${MESSAGES_PORT}"
  messages-service-2:
    <<: *messaging-common-settings
    ports:
      - "8182:${MESSAGES_PORT}"

  facade-service-1:
    <<: *facade-common-settings
    ports:
      - "8001:${FACADE_PORT}"
  facade-service-2:
    <<: *facade-common-settings
    ports:
      - "8002:${FACADE_PORT}"

  consul:
    image: hashicorp/consul:latest
    command: "/bin/sh -c 'sh /consul-population.sh'"
    container_name: consul-server
    volumes:
      - ./consul-population.sh:/consul-population.sh
    ports:
      - "${CONSUL_PORT}:${CONSUL_PORT}"
      - "8600:8600/udp"
    networks:
      - hazelcast-network
      - services-network
    environment:
      HZ_LOGGING_CLUSTER_NAME: "${HZ_LOGGING_CLUSTER_NAME}"
      HZ_LOGGING_MAPPING_NAME: "${HZ_LOGGING_MAPPING_NAME}"

      HZ_MQ_CLUSTER_NAME: "${HZ_MQ_CLUSTER_NAME}"
      HZ_MQ_QUEUE_NAME: "${HZ_MQ_QUEUE_NAME}"

      CONSUL_ESSENTIAL_KEY: "${CONSUL_ESSENTIAL_KEY}"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://${CONSUL_HOST}:${CONSUL_PORT}/v1/kv/${CONSUL_ESSENTIAL_KEY}",
        ]
      interval: 5s
      timeout: 1s
      retries: 3

networks:
  hazelcast-network:
    driver: bridge
    name: hazelcast-network

  services-network:
    driver: bridge
    name: services-network
